# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 37fc2f2b8355c64f0aeb526e07561d2fbf1bdd473aa36026e5558907565526b2d4aaaf7863cd281d18b2dd55483c961924fcd7592f483550409908b25b4e1530

test:
  secret_key_base: e6066919038fde91abd19ccfad919721766d02bc8bf7312d32bbf72ac4c002287c7fc19e4fea7c763cc334c4ceef1342ea8cc9db45847ef556bd92163e29d3b5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
